language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - NEO4J_VERSION="3.0.10"
  - NEO4J_VERSION="3.1.7"
  - NEO4J_VERSION="3.2.9"
  - NEO4J_VERSION="3.3.3"
  - NEO4J_VERSION="3.4.0"
install:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - curl -L http://dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz | tar xz
before_script:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle neo4j-community-$NEO4J_VERSION/bin/neo4j start
  - sleep 10
script: "python setup.py test"
